name: Lint Code Base

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker for Linter
      uses: docker/setup-buildx-action@v1

    - name: Run Super-Linter
      uses: github/super-linter@v4
      env:
        RUN_LOCAL: true
        LINTER_RULES_PATH: .github/linters # ако имате персонализирани правила
        LINTER_DIAGNOSTICS: true
        DOCKERFILE: Dockerfile
        HTML_FILES: index.html
